{% set name = "taxonomy" %}
{% set version = "0.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/onecodex/taxonomy/archive/v{{ version }}.tar.gz
  sha256: 6640eb97f6ec78abe21d8a0d35e2cc930b12ebb70c3240bf71417ad1503965a9

build:
  number: 0
  skip: True  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - maturin
    - python
  run:
    - python

test:
  imports:
    - taxonomy

about:
  home: https://github.com/onecodex/taxonomy/
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: "Python and Rust library for loading, saving, and manipulating taxonomic trees"

