{% set name = "taxonomy" %}
{% set version = "0.8.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/onecodex/taxonomy/archive/v{{ version }}.tar.gz
  sha256: 768f2acd2534565fecd6e87637e2e34a2f1d814d4ff22f22aca5241e36074b98

build:
  number: 0
  skip: True  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - maturin
    - python
  run:
    - python

test:
  imports:
    - taxonomy

about:
  home: https://github.com/onecodex/taxonomy/
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: "Python and Rust library for loading, saving, and manipulating taxonomic trees"

