{% set version = "0.1.53" %}

package:
  name: goat
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/genomehubs/goat-cli/archive/{{ version }}.tar.gz
  sha256: 9d2103bd0252b18d47611794b5ae6ca91ef4258e1e9062250c36392d4f3db5bd

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - rust >=1.52
    - pkg-config # [osx]
  host:
    - openssl
  run:
    

test:
  commands:
    - goat --help
    - goat --version

about:
  home: https://github.com/genomehubs/goat-cli
  license: MIT
  license_file: LICENSE
  summary: |
    Query metadata for any taxon across the tree of life.
  description: |
    A command line interface for the GoaT API, which is a collection of datasets to decorate the genomic tree of life.
